from typing import TypedDict  # Import TypedDict to define the workflow state schema.

from langchain_ollama import ChatOllama  # Import the Ollama chat model.

from langchain_core.tools import tool  # Import the decorator for creating an LLM tool.

from langgraph.graph import StateGraph, START, END  # Import LangGraph components for building the workflow.


class AgentState(TypedDict):  # Define the structure of the agent workflow state.
    question: str  # Store the user's question.
    tool_result: str  # Store the result returned by the tool.
    answer: str  # Store the final answer.


@tool  # Convert the Python function into a tool that the LLM can use.
def get_job_status(job_id: int) -> str:  # Define a tool for retrieving job status.
    """Get the status of a data engineering job."""  # Describe the tool so the LLM knows when to use it.

    jobs = {  # Create simulated job data.
        101: "FAILED - Executor OutOfMemory",  # Store the status for job 101.
        102: "SUCCESS",  # Store the status for job 102.
        103: "RUNNING",  # Store the status for job 103.
    }

    return jobs.get(job_id, "JOB_NOT_FOUND")  # Return the job status or a not-found message.


llm = ChatOllama(  # Create the local Ollama chat model.
    model="llama3.2:3b",  # Use the preferred local model.
    temperature=0,  # Use deterministic responses for easier learning.
)


llm_with_tools = llm.bind_tools([get_job_status])  # Give the LLM access to the job status tool.


def call_agent(state: AgentState) -> AgentState:  # Define the LLM agent node.
    response = llm_with_tools.invoke(state["question"])  # Ask the LLM to respond using the available tool when needed.

    if response.tool_calls:  # Check whether the LLM requested a tool call.
        tool_call = response.tool_calls[0]  # Get the first requested tool call.

        result = get_job_status.invoke(tool_call["args"])  # Execute the requested tool with the LLM-generated arguments.

        state["tool_result"] = result  # Store the tool result in workflow state.

    else:  # Handle cases where the LLM does not request a tool.
        state["answer"] = response.content  # Store the LLM's direct answer.

    return state  # Return the updated workflow state.


def generate_answer(state: AgentState) -> AgentState:  # Define the final answer generation node.
    prompt = f"""Answer the user's question using the tool result.

Question: {state["question"]}

Tool result: {state["tool_result"]}
"""  # Build a prompt containing the question and tool result.

    response = llm.invoke(prompt)  # Ask the LLM to generate the final natural-language answer.

    state["answer"] = response.content  # Store the final answer in workflow state.

    return state  # Return the updated state.


def route_agent(state: AgentState) -> str:  # Decide whether the workflow needs another step.
    if state["tool_result"]:  # Check whether the agent used a tool.
        return "generate_answer"  # Route to final answer generation after tool execution.

    return "finish"  # Finish immediately when no tool was required.


builder = StateGraph(AgentState)  # Create a LangGraph builder using the agent state schema.

builder.add_node("agent", call_agent)  # Register the LLM agent node.

builder.add_node("generate_answer", generate_answer)  # Register the final answer generation node.

builder.add_edge(START, "agent")  # Start the workflow with the agent node.

builder.add_conditional_edges(  # Add conditional routing after the agent node.
    "agent",  # Specify the node from which routing should happen.
    route_agent,  # Specify the function that decides the next step.
    {  # Define the allowed routing destinations.
        "generate_answer": "generate_answer",  # Route tool users to final answer generation.
        "finish": END,  # Finish when no tool is required.
    },
)

builder.add_edge("generate_answer", END)  # Finish the workflow after generating the final answer.

graph = builder.compile()  # Compile the graph into an executable workflow.


initial_state: AgentState = {  # Create the initial workflow state.
    "question": "What is the status of job 101?",  # Provide the user's question.
    "tool_result": "",  # Start without a tool result.
    "answer": "",  # Start without a final answer.
}


result = graph.invoke(initial_state)  # Execute the agent workflow.

print("Tool Result:", result["tool_result"])  # Display the result returned by the tool.

print("Final Answer:", result["answer"])  # Display the final answer generated by the LLM.