# Import the os module.
# We use it to read the Gemini API key.
import os


# Import load_dotenv.
# This loads variables from our .env file.
from dotenv import load_dotenv


# Import Google's Gemini SDK.
from google import genai


# -----------------------------------------
# Load environment variables
# -----------------------------------------

# Load the .env file.
load_dotenv()


# Read the Gemini API key.
API_KEY = os.getenv("GEMINI_API_KEY")


# Stop the program if the API key is missing.
if not API_KEY:
    raise ValueError(
        "GEMINI_API_KEY was not found in the .env file."
    )


# -----------------------------------------
# Create Gemini client
# -----------------------------------------

# Create the Gemini client.
client = genai.Client(api_key=API_KEY)


# Gemini model used for our practical exercises.
MODEL = "gemini-3.7-flash"


# -----------------------------------------
# Function to call Gemini
# -----------------------------------------

def ask_llm(prompt):

    # Send the prompt to Gemini.
    response = client.interactions.create(
        model=MODEL,
        input=prompt
    )

    # Return the text generated by Gemini.
    return response.output_text


# -----------------------------------------
# Agent
# -----------------------------------------

def run_agent(goal):

    # -----------------------------------------
    # Create the initial agent state.
    # -----------------------------------------

    # State stores the information that the agent
    # needs during its execution.
    state = {
        "goal": goal,
        "action": None,
        "observation": None,
        "status": "STARTED"
    }

    # Display the initial state.
    print("\nInitial State:")
    print(state)


    # -----------------------------------------
    # Agent loop
    # -----------------------------------------

    # Allow a maximum of 5 iterations.
    # This prevents an infinite loop.
    for step in range(5):

        print(f"\n--- Iteration {step + 1} ---")


        # -----------------------------------------
        # Ask the LLM to choose an action.
        # -----------------------------------------

        # Give Gemini the current state.
        # This means the LLM knows what has happened so far.
        prompt = f"""
You are a simple AI agent.

Your goal:
{state["goal"]}

Current action:
{state["action"]}

Current observation:
{state["observation"]}

Current status:
{state["status"]}

Available actions:

CHECK_NUMBER
DONE

Choose the next action.

If the number still needs to be checked:
CHECK_NUMBER

If the goal is already completed:
DONE

Return only one action.
"""


        # Ask Gemini for the next action.
        decision = ask_llm(prompt)


        # Remove extra spaces.
        # Convert the response to uppercase.
        decision = decision.strip().upper()


        # -----------------------------------------
        # Update the state with the action.
        # -----------------------------------------

        state["action"] = decision


        # Display the selected action.
        print(f"Action selected: {state['action']}")


        # -----------------------------------------
        # Execute the action.
        # -----------------------------------------

        if decision == "CHECK_NUMBER":

            # Execute the action.
            result = 10 > 5


            # Store the action result
            # as the agent's observation.
            state["observation"] = (
                f"10 > 5 = {result}"
            )


            # Update the status based on the observation.
            if result:
                state["status"] = "COMPLETED"


        # -----------------------------------------
        # Handle DONE decision.
        # -----------------------------------------

        elif decision == "DONE":

            # The agent believes the task is complete.
            state["status"] = "COMPLETED"


        # -----------------------------------------
        # Handle unexpected decisions.
        # -----------------------------------------

        else:

            # If Gemini returns something unexpected,
            # stop the agent instead of continuing blindly.
            state["status"] = "STOPPED"

            print("Unexpected action from Gemini.")

            break


        # -----------------------------------------
        # Display updated state.
        # -----------------------------------------

        print("Updated State:")
        print(state)


        # -----------------------------------------
        # Check whether the task is complete.
        # -----------------------------------------

        if state["status"] == "COMPLETED":

            print("\nAgent finished.")

            break


    # -----------------------------------------
    # Final state
    # -----------------------------------------

    print("\nFinal State:")
    print(state)


# -----------------------------------------
# Program entry point
# -----------------------------------------

if __name__ == "__main__":

    # Give the agent a goal.
    run_agent(
        "Determine whether 10 is greater than 5."
    )