# Import the os module.
# We use it to read the API key from the environment.
import os

# Import load_dotenv.
# This loads variables from our .env file.
from dotenv import load_dotenv

# Import Google's Gemini SDK.
from google import genai


# -----------------------------------------
# Load API key
# -----------------------------------------

# Load variables from the .env file.
load_dotenv()

# Read the Gemini API key.
API_KEY = os.getenv("GEMINI_API_KEY")

# Stop the program if the API key is missing.
if not API_KEY:
    raise ValueError(
        "GEMINI_API_KEY was not found in the .env file."
    )


# -----------------------------------------
# Create Gemini client
# -----------------------------------------

# Create a Gemini client using our API key.
client = genai.Client(api_key=API_KEY)


# Use the current Flash model.
MODEL = "gemini-3.7-flash"


# -----------------------------------------
# Ask Gemini
# -----------------------------------------

def ask_llm(prompt):

    # Send the prompt to Gemini.
    interaction = client.interactions.create(
        model=MODEL,
        input=prompt
    )

    # Return the text generated by Gemini.
    return interaction.output_text


# -----------------------------------------
# Simple Agent
# -----------------------------------------

def run_agent(goal):

    # Display the goal.
    print(f"\nGoal: {goal}\n")

    # Maximum number of iterations.
    # This is an important safety mechanism.
    max_iterations = 5

    # Start the agent loop.
    for step in range(max_iterations):

        print(f"--- Iteration {step + 1} ---")

        # Ask Gemini what the agent should do.
        prompt = f"""
You are an AI agent.

Goal:
{goal}

Available action:
CHECK_NUMBER

CHECK_NUMBER checks whether 10 is greater than 5.

Choose the next action.

Return ONLY:
CHECK_NUMBER

Do not return anything else.
"""

        # Ask Gemini for a decision.
        decision = ask_llm(prompt)

        # Clean the response.
        decision = decision.strip().upper()

        # Display what Gemini decided.
        print(f"LLM decision: {decision}")

        # -----------------------------------------
        # Execute the action
        # -----------------------------------------

        if decision == "CHECK_NUMBER":

            # Execute the action.
            result = 10 > 5

            # Display the action result.
            print(f"Action: CHECK_NUMBER")
            print(f"Observation: 10 > 5 = {result}")

            # The observation tells the agent
            # whether the goal has been achieved.
            if result:

                print("Goal completed.")

                # Stop the agent.
                return

        else:

            # The LLM returned something unexpected.
            print("Unexpected LLM decision.")

            # Stop instead of blindly continuing.
            # This prevents an uncontrolled loop.
            return

    # This executes if the maximum number
    # of iterations is reached.
    print("Agent stopped after maximum iterations.")


# -----------------------------------------
# Program entry point
# -----------------------------------------

if __name__ == "__main__":

    # Give the agent a goal.
    run_agent(
        "Determine whether 10 is greater than 5."
    )