# Import the Ollama Python library.
# This allows Python to communicate with our local Ollama server.
import ollama


# Name of the local LLM.
MODEL = "llama3.2:3b"


# This function sends a prompt to Ollama
# and returns the LLM's response.
def ask_llm(prompt):

    # Send the prompt to the local Ollama model.
    response = ollama.chat(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    # Return only the text generated by the model.
    return response["message"]["content"]


# This is our simple agent.
def run_agent(goal):

    # Display the goal.
    print(f"\nGoal: {goal}\n")

    # Keep track of whether the goal is completed.
    completed = False

    # Allow a maximum of 5 iterations.
    for step in range(5):

        # Ask the LLM what it thinks should happen.
        prompt = f"""
You are a simple AI agent.

Your goal is:
{goal}

You have access to this action:

CHECK_NUMBER

The action checks whether 10 is greater than 5.

Decide what to do next.

If you need to check the number, respond:
CHECK_NUMBER

If the goal has already been completed, respond:
DONE

Respond with only one of these two values.
"""

        # Ask the LLM for its decision.
        decision = ask_llm(prompt)

        # Remove spaces and convert the response to uppercase.
        decision = decision.strip().upper()

        # Display the agent's decision.
        print(f"Iteration {step + 1}: {decision}")

        # If the agent decides to check the number,
        # we execute the action.
        if "CHECK_NUMBER" in decision:

            # This is the environment/action.
            result = 10 > 5

            # Display the result of the action.
            print(f"Action result: 10 > 5 = {result}")

            # The action has given us the information
            # needed to complete the goal.
            if result:

                completed = True

                print("Goal completed.")

                # Stop the agent.
                break

        # If the agent directly says DONE,
        # the agent has decided to finish.
        elif "DONE" in decision:

            completed = True

            print("Agent finished.")

            break

    # If the goal was not completed within 5 iterations,
    # stop the agent.
    if not completed:
        print("Agent stopped after maximum iterations.")


# This block runs when we execute this Python file directly.
if __name__ == "__main__":

    # Give our agent a simple goal.
    run_agent("Determine whether 10 is greater than 5.")