"""
Program 2: Image Understanding using a Vision-Language Model (VLM)

Goal:
    Give an image + text instruction to a Vision-Language Model
    and generate a natural-language description of the image.

Input:
    Image + Text Prompt

Output:
    Natural-language response generated by the VLM.

Model:
    HuggingFaceTB/SmolVLM-256M-Instruct

Why this model?
    - It is a relatively small VLM.
    - It is suitable for learning on a resource-constrained laptop.
    - We are using a pre-trained model.
    - We are NOT training the model.
"""


# =========================================================
# 1. IMPORT LIBRARIES
# =========================================================

# PyTorch is used to run the neural network model.
import torch

# PIL (Python Imaging Library) is used to open and
# manipulate our local image.
from PIL import Image

# AutoProcessor prepares our image and text so that
# the VLM can understand them.
#
# AutoModelForImageTextToText loads a pre-trained model
# that accepts image + text and generates text.
from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
)


# =========================================================
# 2. CONFIGURATION
# =========================================================

# Name of the pre-trained Vision-Language Model
# available on Hugging Face.
MODEL_NAME = "HuggingFaceTB/SmolVLM-256M-Instruct"

# Path to the image that we want the model to understand.
IMAGE_PATH = "data/animal.jpg"


# =========================================================
# 3. SELECT COMPUTING DEVICE
# =========================================================

# Check whether an NVIDIA CUDA GPU is available.
#
# If CUDA is available:
#     use GPU
#
# Otherwise:
#     use CPU
#
# Your laptop will most likely use CPU unless you have
# a compatible NVIDIA GPU configured with PyTorch.
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("=" * 70)
print("IMAGE UNDERSTANDING USING SmolVLM")
print("=" * 70)

print(f"\nUsing device: {DEVICE}")


# =========================================================
# 4. LOAD IMAGE
# =========================================================

print("\nLoading image...")

# Open the image from our local data directory.
image = Image.open(IMAGE_PATH)

# Convert the image to RGB format.
#
# Some image files may use formats such as RGBA or grayscale.
# RGB gives the model a standard 3-channel image.
image = image.convert("RGB")

print(f"Image loaded successfully.")
print(f"Image size: {image.size}")


# =========================================================
# 5. LOAD PROCESSOR
# =========================================================

print("\nLoading processor...")

# The processor is responsible for preparing both:
#
#     1. Image
#     2. Text
#
# for the VLM.
#
# It converts raw inputs into tensors/token IDs that
# the neural network can process.
processor = AutoProcessor.from_pretrained(
    MODEL_NAME
)

print("Processor loaded successfully.")


# =========================================================
# 6. LOAD VISION-LANGUAGE MODEL
# =========================================================

print("\nLoading VLM model...")

# Download/load the pre-trained SmolVLM model.
#
# The first execution may take some time because the
# model needs to be downloaded from Hugging Face.
#
# We are loading an already-trained model.
# We are NOT training it.
model = AutoModelForImageTextToText.from_pretrained(
    MODEL_NAME
)

# Move the model to our selected device.
#
# If DEVICE = "cpu":
#     model runs on CPU
#
# If DEVICE = "cuda":
#     model runs on NVIDIA GPU
model = model.to(DEVICE)

# Put the model into evaluation mode.
#
# This tells PyTorch that we are doing inference,
# not training.
model.eval()

print("VLM model loaded successfully.")


# =========================================================
# 7. CREATE USER MESSAGE
# =========================================================

# A multimodal conversation contains:
#
#     Image
#     +
#     Text instruction
#
# The "image" entry tells the VLM that an image is
# part of the user's message.
#
# The "text" entry contains the instruction/question
# that we want the VLM to answer.
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
            },
            {
                "type": "text",
                "text": (
                    "Describe this image in detail. "
                    "Mention the main subject, "
                    "the environment, "
                    "and what the subject is doing."
                ),
            },
        ],
    }
]


# =========================================================
# 8. CREATE MODEL PROMPT
# =========================================================

print("\nPreparing multimodal prompt...")

# apply_chat_template() converts our structured message
# into the format expected by the VLM.
#
# For example, conceptually:
#
#     User:
#         [IMAGE]
#         Describe this image...
#
# becomes the model-specific prompt format.
#
# add_generation_prompt=True tells the model that
# it should now generate the assistant's answer.
prompt = processor.apply_chat_template(
    messages,
    add_generation_prompt=True,
)

print("Prompt prepared successfully.")


# =========================================================
# 9. PREPARE IMAGE + TEXT FOR THE MODEL
# =========================================================

# The processor now receives:
#
#     prompt
#     +
#     image
#
# and converts them into tensors that the VLM understands.
#
# return_tensors="pt"
#     means:
#     "Return the processed data as PyTorch tensors."
inputs = processor(
    text=prompt,
    images=image,
    return_tensors="pt",
)


# =========================================================
# 10. MOVE INPUT TENSORS TO THE SAME DEVICE
# =========================================================

# The model is already on DEVICE.
#
# Therefore, the input tensors must also be moved
# to the same device.
#
# Example:
#
#     Model  → CPU
#     Inputs → CPU
#
# or
#
#     Model  → GPU
#     Inputs → GPU
inputs = inputs.to(DEVICE)


# =========================================================
# 11. GENERATE MODEL RESPONSE
# =========================================================

print("\nGenerating response...")

# We are performing inference only.
#
# torch.no_grad() tells PyTorch that we do not need
# gradients because we are not training the model.
#
# This reduces unnecessary memory usage.
with torch.no_grad():

    # generate() asks the VLM to generate new tokens
    # based on the image and our text instruction.
    #
    # max_new_tokens=100:
    #     Limit the generated response to approximately
    #     100 newly generated tokens.
    #
    # do_sample=False:
    #     Use deterministic generation for this learning
    #     example instead of random sampling.
    generated_ids = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False,
    )


# =========================================================
# 12. CONVERT TOKEN IDs INTO TEXT
# =========================================================

# The model does not directly return a Python string.
#
# It generates token IDs.
#
# Example conceptually:
#
#     [128, 452, 91, 733, ...]
#
# batch_decode() converts those token IDs into
# human-readable text.
generated_text = processor.batch_decode(
    generated_ids,
    skip_special_tokens=True,
)[0]


# =========================================================
# 13. DISPLAY RESULT
# =========================================================

print("\n" + "=" * 70)
print("VLM IMAGE UNDERSTANDING RESULT")
print("=" * 70)

print(generated_text)

print("=" * 70)