import ollama


# =========================================================
# Simple request
# =========================================================

response = ollama.chat(
    model="llama3.2:3b",

    messages=[
        {
            "role": "user",
            "content": "What is Apache Spark?"
        }
    ]
)


# =========================================================
# Response
# =========================================================

print("========== RESPONSE ==========")

print(
    response["message"]["content"]
)


# =========================================================
# Token information
#
# prompt_eval_count:
#   Number of input tokens processed by the model.
#
# eval_count:
#   Number of output tokens generated by the model.
# =========================================================

print("\n========== TOKEN INFORMATION ==========")

print(
    "Input tokens :",
    response.get("prompt_eval_count")
)

print(
    "Output tokens:",
    response.get("eval_count")
)